spring.application.name=TicketBooking
server.port=${PORT:8080}

#spring.datasource.url=jdbc:mysql://mysql:3306/ticket_booking_system
#spring.datasource.username=root
#spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

razorpay.key.id=rzp_test_Sx2M5fBCdGg9nJ
razorpay.key.secret=P4QBJG9hMnCMDxh0gZlaaRm3

#spring.kafka.bootstrap-servers=kafka:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

server.forward-headers-strategy=framework

spring.kafka.consumer.group-id=ticket-booking-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=true
spring.cache.type=redis

logging.level.org.springframework.cache=DEBUG
logging.level.org.springframework.data.redis=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=newidagent@gmail.com
spring.mail.password=qmpw uqpu bpzq nalv

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true